### PR TITLE
feat(output): enable json output for amtinfo

### PR DESCRIPTION
**Pull request by SvenDowideit**
for #22 

```
sudo ./rpc amtinfo -json 
{
  "AMT": "15.0.30",
  "Build Number": "1776",
  "Control Mode": "pre-provisioning state",
  "DNS Suffix": "",
  "DNS Suffix (OS)": "",
  "Hostname (OS)": "p1",
  "RAS": {
    "NetworkStatus": "unknown",
    "RemoteStatus": "not connected",
    "RemoteTrigger": "user initiated",
    "MPSHostname": ""
  },
  "SKU": "16392",
  "UUID": "a94a55cc-267e-11b2-a85c-e2a9c1f3470e",
  "Wired Adapter": {
    "IsEnabled": true,
    "LinkStatus": "down",
    "DHCPEnabled": true,
    "DHCPMode": "active",
    "IPAddress": "0.0.0.0",
    "MACAddress": "00:00:00:00:00:00"
  },
  "Wireless Adapter": {
    "IsEnabled": false,
    "LinkStatus": "down",
    "DHCPEnabled": true,
    "DHCPMode": "passive",
    "IPAddress": "0.0.0.0",
    "MACAddress": "00:00:00:00:00:00"
  }
}
```

### CODE REVIEW

**Comment by SvenDowideit** [comment]
@rsdmike yup, tell me what you want the "semantic pull request bit to look like"

**Comment by rsdmike** [comment]
I love it! @Craig-Spencer-12 was looking at working on this, but you beat him to it! If you could add a just a few unit tests around that json flag output that would be awesome. For the commit, something like `feat(output): adds json output for amtinfo commands`

**Review by Craig-Spencer-12 — APPROVED** [review]
Finished this last week but was waiting to merge when I had finished implementing -json throughout rpc-go instead of just amtinfo. Functionally our changes work the same but I think your implementation is a bit cleaner. Good stuff!

**Comment by SvenDowideit** [comment]
@Craig-Spencer-12 yup, staring at the cert code now, thinking about how best to wrangle that - mixing data and presentation layer is always a bit fraught :)

**Comment by SvenDowideit** [comment]
@rsdmike and @Craig-Spencer-12 so the next issue we have, is we want _all_ output to be json parseable - including the error cases

idk, I can continue to poke this, or I can wait to see your next work :)

**Comment by Craig-Spencer-12** [comment]
> @rsdmike and @Craig-Spencer-12 so the next issue we have, is we want _all_ output to be json parseable - including the error cases
> 
> idk, I can continue to poke this, or I can wait to see your next work :)

This should be a simple one-liner to update the format type in main.go. I have the changes made and will be testing them after the break!

**Review by rsdmike — APPROVED** [review]

**Pull request merged**
